name: prometheus-node-exporter 
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Prometheus exporter for hardware and OS metrics
description: |
  Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written in Go with pluggable metric collectors.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  node-export:
    command: usr/bin/node_exporter
    daemon: simple

parts:
  node-exporter:
    plugin: nil
    source: https://github.com/prometheus/node_exporter
    source-type: git
    source-tag: v1.6.1
    build-snaps:
       - go
    override-build: |
        make build
        mkdir -p $CRAFT_PART_INSTALL/usr/bin
        cp node_exporter $CRAFT_PART_INSTALL/usr/bin

plugs:
  system-observe:
  system-trace:


